# Ubuntu scan profile Level_1
openscap_debian_profile: xccdf_org.ssgproject.content_profile_cis_level1_server
openscap_debian_results: cis_level1_server.xml
openscap_debian_report: cis_level1_server.html